# Use a imagem de base selenim/node-chromium
FROM selenium/node-chrome:latest

# Variável de ambiente para o idioma Português
ENV LANG pt-BR.UTF-8

# Instalaçãp do pacote de idioma em Português
USER root
RUN apt update
RUN apt install -y locales locales-all && locale-gen pt-BR.UTF-8 && dpkg-reconfigure locales

ARG CHROME_VERSION="google-chrome-stable --lang=pt-BR"